### ISSUE TITLE
tutorials.yaml のリファクタリングをしたい

### ISSUE THREAD

**Issue by shukawam** [oracle-japan/ocitutorials#163]
認証トークン等の入れ替えにおける影響を最小化できるようにリファクタリングしたい。

以下のログイン/プッシュ手順は、素直に Artifact Repository/OCIR を使えば不要になるはず。

```yaml
  - type: Command                   
    name: "Login to OCIR"  
    shell: bash                    
    runAs: root          
    command: |
      docker login nrt.ocir.io -u orasejapan/oracleidentitycloudservice/takuya.niita@oracle.com -p ${OCIRCRED}
    onFailure:                     
      - type: Command
        command: |
          echo "Failured Login to OCIR"
        runAs: root
# ...
  - type: Command
    name: "Docker Push to OCIR"
    command: |
      docker push nrt.ocir.io/orasejapan/oci-tutorials/staging-env:${BUILDRUN_HASH}
    onFailure:
      - type: Command
        command: |
          echo "Failured docker push"
        runAs: root
```

かつ、OCIR のリポジトリ情報も DevOps 側に隠蔽できるはず

```yaml
  - type: Command
    name: "Docker Build"
    command: |
      docker build -t nrt.ocir.io/orasejapan/oci-tutorials/staging-env:${BUILDRUN_HASH} .
    onFailure:
      - type: Command
        command: |
          echo "Failured docker build"
        runAs: root
```
